version: '3'

services:
  node:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: node
    networks:
      - nodenet
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet

networks:
  nodenet:
    driver: bridge