version: '3'

services:
  node:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && node index.js"
    networks:
      - nodenet
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - nodenet

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks: 
      - nodenet
    ports: 
      - "8080:80"

networks:
  nodenet:
    driver: bridge